services:
  yasa-processor:
    build: .
    volumes:
      - ./data/input:/app/data/input
      - ./data/output:/app/data/output
    environment:
      - EDF_FILENAME=EMU1371_Day02_1_5006_to_5491.edf